// Purpose: RED-phase tests for Phase 3e sub-cluster D — golden-file byte-equality
//          (T3e.8, T3e.9). Pin sample_receipt_data.json PDF/PNG output to the
//          committed examples/golden/sample_receipt_data.golden.{pdf,png} bytes.
// Categories: Snapshot — Skia rasterisation differs across platforms (font hinting,
//             subpixel positioning, compression library version), so the gate runs
//             on Linux CI only per the CLAUDE.md hard rule. macOS / Windows runs
//             skip cleanly via Assert.Skip rather than failing.
// Edge cases: When a golden file is missing on a Linux run, Assert.Fail surfaces a
//             clear regeneration instruction instead of returning empty bytes
//             that would make the byte-equality assertion fail with a confusing
//             zero-length diff.
// Regen mode: Set environment variable RECEIPT_REGEN_GOLDENS=1 (and
//             RECEIPT_GOLDEN_OUTPUT_DIR=<absolute path to examples/golden>) to write
//             the produced bytes to the source tree instead of asserting. The
//             dedicated GitHub Actions workflow .github/workflows/regen-goldens.yml
//             sets both vars and opens a PR with the new bytes; manual local regen
//             on Linux works the same way.

using ReceiptToolkit.Contracts;
using ReceiptToolkit.Core.Generation;
using ReceiptToolkit.Core.Rendering.Assets;
using ReceiptToolkit.Core.Tests.Rendering.Sections;
using ReceiptToolkit.Core.Tests.Time;

namespace ReceiptToolkit.Core.Tests.Generation;

public sealed class ReceiptGeneratorGoldenTests
{
    // The golden clock instant is part of the PDF /CreationDate metadata; any
    // change to this value invalidates the committed sample_receipt_data.golden.pdf
    // and requires regeneration. Choose a memorable, fixed instant.
    private static readonly DateTimeOffset GoldenClock =
        new(2025, 5, 18, 10, 42, 0, TimeSpan.Zero);

    private const string GoldenPdfFile = "sample_receipt_data.golden.pdf";
    private const string GoldenPngFile = "sample_receipt_data.golden.png";
    private const string RegenEnvVar = "RECEIPT_REGEN_GOLDENS";
    private const string RegenOutputDirEnvVar = "RECEIPT_GOLDEN_OUTPUT_DIR";

    // T3e.8 — Sample-fixture PDF byte-equal to the committed golden PDF on Linux.
    [Fact]
    public async Task GeneratePdfAsync_MatchesGoldenBytes_OnLinux()
    {
        SkipIfNotLinux();

        ReceiptData data = SectionTestBase.LoadSampleData();
        using var fonts = new FontProvider();
        using var generator = new ReceiptGenerator(new FixedClock(GoldenClock), fonts);

        byte[] actual = await generator.GeneratePdfAsync(data, TestContext.Current.CancellationToken);
        AssertOrRegenerate(GoldenPdfFile, actual);
    }

    // T3e.9 — Sample-fixture PNG byte-equal to the committed golden PNG on Linux.
    [Fact]
    public async Task GeneratePngAsync_MatchesGoldenBytes_OnLinux()
    {
        SkipIfNotLinux();

        ReceiptData data = SectionTestBase.LoadSampleData();
        using var fonts = new FontProvider();
        using var generator = new ReceiptGenerator(new FixedClock(GoldenClock), fonts);

        byte[] actual = await generator.GeneratePngAsync(data, TestContext.Current.CancellationToken);
        AssertOrRegenerate(GoldenPngFile, actual);
    }

    private static void SkipIfNotLinux()
    {
        if (!OperatingSystem.IsLinux())
        {
            Assert.Skip(
                "Golden tests are gated to Linux CI per the CLAUDE.md hard rule. " +
                "SkiaSharp rasterisation differs across platforms (font hinting, " +
                "subpixel positioning), so byte-equality is enforced on Linux only.");
        }
    }

    private static void AssertOrRegenerate(string fileName, byte[] actual)
    {
        if (Environment.GetEnvironmentVariable(RegenEnvVar) == "1")
        {
            string? outDir = Environment.GetEnvironmentVariable(RegenOutputDirEnvVar);
            if (string.IsNullOrEmpty(outDir))
            {
                Assert.Fail(
                    $"{RegenEnvVar}=1 was set but {RegenOutputDirEnvVar} is empty. " +
                    $"Set it to the absolute path of the source examples/golden directory " +
                    $"(e.g. \"$GITHUB_WORKSPACE/examples/golden\") so regenerated bytes land " +
                    $"in the source tree, not the test bin output.");
            }

            Directory.CreateDirectory(outDir);
            string outPath = Path.Combine(outDir, fileName);
            File.WriteAllBytes(outPath, actual);
            Assert.Skip(
                $"Regenerated {fileName} ({actual.Length} bytes) → {outPath}. " +
                $"Commit the bytes to lock the golden; subsequent runs will assert byte-equality.");
            return;
        }

        byte[] expected = LoadGoldenOrFail(fileName);
        Assert.Equal(expected, actual);
    }

    private static byte[] LoadGoldenOrFail(string fileName)
    {
        string path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "golden", fileName);
        if (!File.Exists(path))
        {
            Assert.Fail(
                $"Golden file missing: {path}. " +
                $"Trigger the regen-goldens workflow (or run locally on Linux with " +
                $"{RegenEnvVar}=1 and {RegenOutputDirEnvVar}=<repo>/examples/golden) to produce " +
                $"the bytes, then commit them. Phase 3e divergence #23 documents this gap.");
        }

        return File.ReadAllBytes(path);
    }
}
